manifest:
  defaults:
    revision: v0.3
  remotes:
    - name: zmkfirmware
      url-base: https://github.com/zmkfirmware
    - name: cormoran
      url-base: https://github.com/cormoran
    - name: petejohanson
      url-base: https://github.com/petejohanson
    - name: caksoylar
      url-base: https://github.com/caksoylar
    - name: geeksville
      url-base: https://github.com/geeksville
    - name: nuovotaka
      url-base: https://github.com/nuovotaka
    - name: takumibaya
      url-base: https://github.com/takumibaya
  projects:
    - name: zmk
      remote: cormoran
      revision: v0.3+custom-studio-protocol
      import: app/west.yml
    - name: toucan-custom-studioo-rpc
      remote: takumibaya
      revision: main
    - name: cirque-input-module
      remote: geeksville
      revision: main
    - name: zmk-rgbled-widget
      remote: caksoylar
      revision: main
    - name: zmk-input-gestures
      url: https://github.com/takumibaya/zmk-input-gestures
      revision: main
    - name: zmk-pointing-acceleration-alpha
      remote: nuovotaka
      revision: main
  self:
    path: config
